const Data = {
    pieces: [
        {
            id: 1,
            vin: "bla bla bla",
            reference: "839274R09Y90",
            description: {
                Largeur: 125,
                Hauteur: 80,
                Type: "R",
                Diamètre: 17,
                Indice_de_charge: 99,
                Indice_de_vitesse: 80,
            },
            typeVehicule: " ",
            categoryId: 0,
            fournisseurId: 0,
            panierId: 0,
            createdAt: "01/09/2022",
            updatedAt: "02/09/2022",
            quantite: 10,

            cover: "./assets/piece1.jpg",
            name: "Pneus Linglong T010 125/80 R17 99M",
            prix: 2000,
        },
        {
            id: 2,
            vin: "bla bla bla",
            reference: "O890274R09Y90",
            description: {
                Largeur: 145,
                Hauteur: 70,
                Type: "R",
                Diamètre: 12,
                Indice_de_charge: 69,
                Indice_de_vitesse: 40,
            },
            typeVehicule: " ",
            categoryId: 0,
            fournisseurId: 0,
            panierId: 0,
            createdAt: "01/09/2022",
            updatedAt: "02/09/2022",
            quantite: 20,

            cover: "./assets/piece2.jpg",
            name: "APlus A609 145/70 R12 69T Pneus été",
            prix: 3100,
        },
        {
            id: 3,
            vin: "bla bla bla",
            reference: "RO8904R09Y90",
            description: {
                Unité_quantitative: "Set d'essieu",
                Gamme_de_produits: "PREMIER ECO FRICTION",
                Indicateur_usure: "contact de signal d'usure inclus",
                Longueur_mm: 160.1,
                Hauteur_mm: 64.6,
                Épaisseur_mm: 20.2,
                
            },
            typeVehicule: " ",
            categoryId: 0,
            fournisseurId: 0,
            panierId: 0,
            createdAt: "01/09/2022",
            updatedAt: "02/09/2022",
            quantite: 5,

            cover: "./assets/piece3.jpg",
            name: "FERODO PREMIER ECO FRICTION FDB4433 Jeu de plaquettes de frein",
            prix: 4000,
        },
        {
            id: 4,
            vin: "bla bla bla",
            reference: "220100S",
            description: {
                Filetage: "M 16 x 1,50 x 12",
                Longueur_mm: 15.5,
                Ouverture_de_la_clé: "8 x 8",
                Article_complémentaire_et_Info_complémentaire_2: "avec bague d'étanchéité",
                Type_emballage: "Emballage en blister",
                CORTECO: "Vis-bouchon, carter d'huile",
                
            },
            typeVehicule: " ",
            categoryId: 0,
            fournisseurId: 0,
            panierId: 0,
            createdAt: "01/09/2022",
            updatedAt: "02/09/2022",
            quantite: 5,

            cover: "./assets/piece4.jpg",
            name: "CORTECO 220100S Vis-bouchon, carter d'huile",
            prix: 50,
        },

    ],
}
export default Data
