const Data = {
  productItems: [
    {
      id: 1,
      vin: "bla bla bla",
      reference: "839274R09Y90",
      description: {
        Largeur: 125,
        Hauteur: 80,
        Type: "R",
        Diamètre: 17,
        Indice_de_charge: 99,
        Indice_de_vitesse: 80,
      },
      typeVehicule: "3",
      categoryId: 0,
      fournisseurId: 0,
      panierId: 0,
      createdAt: "01/09/2022",
      updatedAt: "02/09/2022",
      quantite: 10,

      cover: "./images/flash/piece1.jpg",
      name: "Pneus Linglong T010 125/80 R17 99M",
      price: 2000,
    },
    {
      id: 2,
      vin: "bla bla bla",
      reference: "O890274R09Y90",
      description: {
        Largeur: 145,
        Hauteur: 70,
        Type: "R",
        Diamètre: 12,
        Indice_de_charge: 69,
        Indice_de_vitesse: 40,
      },
      typeVehicule: "3",
      categoryId: 0,
      fournisseurId: 0,
      panierId: 0,
      createdAt: "01/09/2022",
      updatedAt: "02/09/2022",
      quantite: 20,

      cover: "./images/flash/piece2.jpg",
      name: "APlus A609 145/70 R12 69T Pneus été",
      price: 3100,
    },
    {
      id: 3,
      vin: "bla bla bla",
      reference: "RO8904R09Y90",
      description: {
        Unité_quantitative: "Set d'essieu",
        Gamme_de_produits: "PREMIER ECO FRICTION",
        Indicateur_usure: "contact de signal d'usure inclus",
        Longueur_mm: 160.1,
        Hauteur_mm: 64.6,
        Épaisseur_mm: 20.2,
      },
      typeVehicule: "3",
      categoryId: 0,
      fournisseurId: 0,
      panierId: 0,
      createdAt: "01/09/2022",
      updatedAt: "02/09/2022",
      quantite: 5,

      cover: "./images/flash/piece3.jpg",
      name: "FERODO PREMIER ECO FRICTION FDB4433 Jeu de plaquettes de frein",
      price: 4000,
    },
    {
      id: 4,
      vin: "bla bla bla",
      reference: "220100S",
      description: {
        Filetage: "M 16 x 1,50 x 12",
        Longueur_mm: 15.5,
        Ouverture_de_la_clé: "8 x 8",
        Article_complémentaire_et_Info_complémentaire_2:
          "avec bague d'étanchéité",
        Type_emballage: "Emballage en blister",
        CORTECO: "Vis-bouchon, carter d'huile",
      },
      typeVehicule: "3",
      categoryId: 0,
      fournisseurId: 0,
      panierId: 0,
      createdAt: "01/09/2022",
      updatedAt: "02/09/2022",
      quantite: 5,

      cover: "./images/flash/piece4.jpg",
      name: "CORTECO 220100S Vis-bouchon, carter d'huile",
      price: 50,
    },
    {
      id: 5,
      vin: "bla bla bla",
      reference: "0 092 S5A 080",
      description: {
        txt: "12V 70Ah 760A B13 Batterie AGM",
        Capacité_de_batterie: "70 AH",
        Rebord_de_fixation: "B13",
        Voltage: "12 V",
        Longueur_mm: 278,
        Hauteur_mm: 190,
        DIN_ISO: "L3",
      },
      typeVehicule: "3",
      categoryId: 0,
      fournisseurId: 0,
      panierId: 0,
      createdAt: "01/09/2022",
      updatedAt: "02/09/2022",
      quantite: 5,

      cover: "./images/flash/piece5.jpg",
      name: "BOSCH S5 0 092 S5A 080 Batterie de démarrage",
      price: 50,
    },
  ],
};
/*   {
    productItems: [
      {
        id: 1,
        discount: 50,
        cover: "./images/flash/flash-1.png",
        name: "Shoes",
        price: 100,
        description:
          "Harvest Vases are a reinterpretation of peeled fruits and vegetables as functional objects. The surfaces appear to be sliced and pulled aside, allowing room for growth.",
      },
      {
        id: 2,
        discount: 40,
        cover: "./images/flash/flash-2.png",
        name: "Watch",
        price: 20,
        description:
          "Harvest Vases are a reinterpretation of peeled fruits and vegetables as functional objects. The surfaces appear to be sliced and pulled aside, allowing room for growth.",
      },
      {
        id: 3,
        discount: 40,
        cover: "./images/flash/flash-3.png",
        name: "Smart Mobile Black",
        price: 200,
        description:
          "Harvest Vases are a reinterpretation of peeled fruits and vegetables as functional objects. The surfaces appear to be sliced and pulled aside, allowing room for growth.",
      },
      {
        id: 4,
        discount: 40,
        cover: "./images/flash/flash-4.png",
        name: "Smart Watch Black",
        price: 50,
        description:
          "Harvest Vases are a reinterpretation of peeled fruits and vegetables as functional objects. The surfaces appear to be sliced and pulled aside, allowing room for growth.",
      },
      {
        id: 5,
        discount: 50,
        cover: "./images/flash/flash-1.png",
        name: "Shoes",
        price: 100,
        description:
          "Harvest Vases are a reinterpretation of peeled fruits and vegetables as functional objects. The surfaces appear to be sliced and pulled aside, allowing room for growth.",
      },
      {
        id: 6,
        discount: 50,
        cover: "./images/flash/flash-3.png",
        name: "Shoes",
        price: 100,
        description:
          "Harvest Vases are a reinterpretation of peeled fruits and vegetables as functional objects. The surfaces appear to be sliced and pulled aside, allowing room for growth.",
      },
    ],
  }; */
export default Data;
